Update GitHub Actions to new `r-lib` upgrades
- update all GitHub Action workflow *.yaml files
- fixes SomaLogic/SomaDataIO#26

diff --git a/.github/workflows/document.yaml b/.github/workflows/document.yaml
--- a/.github/workflows/document.yaml
+++ b/.github/workflows/document.yaml
@@ -1,30 +1,64 @@
+# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
+# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
+# heavily modified from: `github.com/r-lib/actions/examples/document.yaml`
 on:
-  issue_comment:
-    types: [created]
-name: Commands
+  push:
+    branches: [main, master]
+    paths: ["R/**"]
+  pull_request:
+    branches: [main, master]
+    paths: ["R/**"]
+
+name: Document
+
 jobs:
   document:
-    if: startsWith(github.event.comment.body, '/document')
-    name: document
-    runs-on: macOS-latest
+    runs-on: ubuntu-latest
+
     env:
       GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
+      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
+
     steps:
-      - uses: actions/checkout@v2
-      - uses: r-lib/actions/pr-fetch@v1
+      - name: Checkout repo
+        if: github.event_name != 'pull_request'
+        uses: actions/checkout@v3
         with:
-          repo-token: ${{ secrets.GITHUB_TOKEN }}
-      - uses: r-lib/actions/setup-r@master
-      - name: Install dependencies
-        run: Rscript -e 'install.packages(c("remotes", "roxygen2"))' -e 'remotes::install_deps(dependencies = TRUE)'
-      - name: Document
-        run: Rscript -e 'roxygen2::roxygenise()'
-      - name: commit
+          fetch-depth: 0
+          clean: true
+
+      - name: Checkout repo
+        if: github.event_name == 'pull_request'
+        uses: actions/checkout@v3
+        with:
+          ref: ${{ github.event.pull_request.head.sha }}
+          fetch-depth: 0
+          clean: true
+
+      - name: Fix Detached HEAD
         run: |
-          git config --local user.email "actions@github.com"
-          git config --local user.name "GitHub Actions"
-          git add man/\* NAMESPACE
-          git commit -m 'Document'
-      - uses: r-lib/actions/pr-push@v1
+          git switch $BRANCH_NAME
+
+      - name: Setup R
+        uses: r-lib/actions/setup-r@v2
         with:
-          repo-token: ${{ secrets.GITHUB_TOKEN }}
+          use-public-rspm: true
+
+      - name: Install dependencies
+        uses: r-lib/actions/setup-r-dependencies@v2
+        with:
+          extra-packages: any::roxygen2
+          needs: roxygen2
+
+      - name: Document
+        run: roxygen2::roxygenise()
+        shell: Rscript {0}
+
+      - name: Commit and push changes
+        run: |
+          git config --local user.name "$GITHUB_ACTOR"
+          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
+          git add man/\* NAMESPACE DESCRIPTION
+          git commit -m "Update documentation" || echo "No changes to commit"
+          git pull --ff-only
+          git push origin
